licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:public"])


cc_library(
    name = "defines",
    srcs = ["cc/kernels/defines.hpp"],
    visibility = ["//tfg_custom_ops/compute_keys:__pkg__"],
)


cc_library(
    name = "gpu_device",
    srcs = ["cc/kernels/gpu_device.hpp"],
    visibility = ["//tfg_custom_ops/compute_keys:__pkg__"],
    )

cc_library(
    name = "cuda_kernel_utils",
    srcs = ["cc/kernels/cuda_kernel_utils.h"],
    visibility = ["//tfg_custom_ops/compute_keys:__pkg__"],
    )


cc_library(
    name = "grid_utils",
    srcs = ["cc/kernels/grid_utils.h"],
    visibility = ["//tfg_custom_ops/compute_keys:__pkg__"],
    )


cc_library(
    name = "math_helper",
    srcs = ["cc/kernels/math_helper.h"],
    visibility = ["//tfg_custom_ops/compute_keys:__pkg__"],
    )



cc_library(
    name = "tf_gpu_device",
    srcs = ["cc/kernels/tf_gpu_device.hpp"],
    visibility = ["//tfg_custom_ops/compute_keys:__pkg__"],
    )


cc_library(
    name = "tf_utils",
    srcs = ["cc/kernels/tf_utils.hpp"],
    visibility = ["//tfg_custom_ops/compute_keys:__pkg__"],
    )

